{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### CSE-5334 Project\n",
    "### Data Mininig \n",
    "\n",
    "### BoardGameGeek Reviews: This report is written in Jupiter notebook,\n",
    "##### By: Amnah Abdelrahman\n",
    "##### Date: May 11, 2020\n",
    "\n",
    "\n",
    "\n",
    "The goal of this project is to predict the rating of a board-game given a review, using text analysis tools and machine learning methods. The data of size 1 GB is taken form Kaggle: https://www.kaggle.com/jvanelteren/boardgamegeek-reviews#2019-05-02.csv. The data spread over 3 CSV files:\n",
    "* games_detailed_info.csv (with 56 columns and 17063) : This file has a many detials about all type of board games, exmaples: are the game rank, number of plyers, number of user rated, time requried for the game, desiner and some instructions.\n",
    "***\n",
    "* bgg-13m-reviews.csv (with 6 columns and 13170073): provids the user names with there reviews and rating for each game.\n",
    "***\n",
    "* 2019-05-02.csv (9 columns and 17065) : This file contain more precisis information for each game the game name ,year, rank and number of users rated.\n",
    "***\n",
    "\n",
    "\n",
    "## Getting Started\n",
    "\n",
    "These instruction will guid to deploy the project in you local machine \n",
    "\n",
    "### Prerequisites\n",
    "\n",
    "From your terminla you to install the follwing:\n",
    "\n",
    "   * pip 3 installer [https://pip.pypa.io/en/stable/installing/]\n",
    "   * Python 3 [https://www.python.org/downloads/]\n",
    "   * SKlearn [https://scikit-learn.org/stable/install.html]\n",
    "   \n",
    "You can use this link for an easy steps [https://evansdianga.com/install-pip-osx/]\n",
    "\n",
    "\n",
    "### Installing\n",
    "Frist you will need to downlaod the data from https://www.kaggle.com/jvanelteren/boardgamegeek-reviews#2019-05-02.csv in you local machine, write the right path for your files in you machine. \n",
    "Now from you terminal run jupyter notbook, \n",
    "it should open a page in your browser. \n",
    "\n",
    "## Running the tests\n",
    "\n",
    "Downlaod the file in your computer then open it from the jupyter notebook tab.\n",
    "Then from Kernal you can run the codes.\n",
    "\n",
    "\n",
    "## Deployment\n",
    "\n",
    "\n",
    "This jupyter Notebook has 5 main sections:\n",
    "1. Load the file contents, Data description and Data Processig,\n",
    "    this section has alot of infoamtion about most of the data features, training and testing set slpiting \n",
    "2.  Text Analysis and Feature extarction Vector (CountVectorizer, TfidfVectorizer) \n",
    "3.  Machine Learning Model Selection \n",
    "      \n",
    "      *  Linear and Logistic Regression <u>[linear_model.LogisticRegression]</u>\n",
    "      3. Linear Classifiers  <u>[svm.LinearSVC]</u>\n",
    "      4. Support Vector Machine <u>[SGDClassifier]</u>\n",
    "      5. Linear Support Vector Machine <u>[svm.LinearSVC]</u>\n",
    "      6. Naive Bayes Classifier <u>[MultinomialNB]</u>\n",
    "      7. Decision Tree Classifier <u>[DecisionTreeClassifier]</u>\n",
    "      8. Ensemble Model \n",
    "            - Boosting Models <u>[ensemble.AdaBoostClassifier]</u>\n",
    "            - Random Forest Classifier <u>[ensemble.RandomForestClassifier]</u>          \n",
    "            \n",
    "4.  Model Evaluation and Optimazation (<u>using GridSearch, RandomizedSearchCV</u>)\n",
    "\n",
    "The end of the file is result descution, cahhlenges and refrences \n",
    "\n",
    "\n",
    "## Refrences \n",
    "\n",
    "* https://www.kaggle.com/ngrq94/boardgamegeek-reviews-data-preparation\n",
    " \n",
    "* https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html\n",
    " \n",
    "* https://medium.com/@galen.ballew/board-games-meet-machine-learning-34026870f8d5\n",
    " \n",
    "* https://towardsdatascience.com/multi-class-text-classification-model-comparison-and-selection-5eb066197568\n",
    "\n",
    "* https://towardsdatascience.com/columntransformer-meets-natural-language-processing-da1f116dd69f   \n",
    "\n",
    "* https://www.mooc-list.com/course/build-board-game-predictor-using-machine-learning-eduonix\n",
    " \n",
    "* https://monkeylearn.com/text-classification/\n",
    "\n",
    "* https://www.kaggle.com/emanueleamcappella/random-forest-hyperparameters-tuning\n",
    "\n",
    "* https://guneetkohli.github.io/machine-learning/board-game-reviews/#.XqK_ky-z1QI\n",
    "\n",
    "* https://docs.google.com/viewer?a=v&pid=sites&srcid=YWltcy5hYy50enxhaW1zLXRhbnphbmlhLWFyY2hpdmV8Z3g6YmI1ODkxYjEwOGQ4NGVi\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
